In [2]:
import numpy as np
class McCullochPittsNeuron:
    def __init__(self, threshold):
        """
        Inicializa la neurona con un umbral.
        :param threshold: Umbral para la función de activación
        """
        self.threshold = threshold

    def activate(self, inputs): # F(X)
        """
        Calcula la salida de la neurona basada en las entradas.
        :param inputs: Lista o array de entradas (0 o 1)
        :return: Salida de la neurona (0 o 1)
        """
        # Calcula la suma de las entradas
        print(inputs)
        weighted_sum = inputs.sum() #  G(X) suma todos los elementos
        
        # Aplica la función de activación (umbral)
        activacion = 0 
        if weighted_sum >= self.threshold: 
            activacion = 1
        return activacion

# Configura el umbral para la función AND

threshold = 2  # Umbral para que la suma sea al menos 2 para producir salida 1

# Crea la neurona
neuron = McCullochPittsNeuron(threshold)

# Prueba la neurona con todas las combinaciones de entradas para la función AND
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1],
    [1, 1],
    [1, 1]
])

# Imprime las salidas para cada combinación de entradas
for inp in inputs:
    output = neuron.activate(inp)
    print(f"Entrada: {inp}, Salida: {output}")

[0 0]
Entrada: [0 0], Salida: 0
[0 1]
Entrada: [0 1], Salida: 0
[1 0]
Entrada: [1 0], Salida: 0
[1 1]
Entrada: [1 1], Salida: 1
[1 1]
Entrada: [1 1], Salida: 1
[1 1]
Entrada: [1 1], Salida: 1


## Ejercicio1: 

### Diseñar e implementar en una clase una unidad McCulloch–Pitts capaz de reconocer la función AND y OR para 3 variables.

In [4]:
import numpy as np
class McCullochPittsNeuron:
    def __init__(self, threshold): #UMBRAL
      
        self.threshold = threshold

    def activate(self, inputs): # F(X)
        
        # Calcula la suma de las entradas
        print(inputs)
        weighted_sum = inputs.sum() #  G(X) suma todos los elementos
        
        # Aplica la función de activación (umbral)
        activacion = 0 
        if weighted_sum >= self.threshold: 
            activacion = 1
        return activacion

# Configura el umbral para la función AND

threshold = 1  # Umbral para que la suma sea al menos 2 para producir salida 1  *****************  1=OR 3=AND  ***********************

# Crea la neurona
neuron = McCullochPittsNeuron(threshold)

# Prueba la neurona con todas las combinaciones de entradas para la función AND
inputs = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],#mm
    [1, 1, 0],
    [1, 0, 1],
    [1, 1, 1],
    [0, 0, 0],
])

# Imprime las salidas para cada combinación de entradas
for inp in inputs:
    output = neuron.activate(inp)
    print(f"Entrada: {inp}, Salida: {output}")

[0 0 0]
Entrada: [0 0 0], Salida: 0
[1 0 0]
Entrada: [1 0 0], Salida: 1
[0 1 0]
Entrada: [0 1 0], Salida: 1
[0 0 1]
Entrada: [0 0 1], Salida: 1
[1 1 0]
Entrada: [1 1 0], Salida: 1
[1 0 1]
Entrada: [1 0 1], Salida: 1
[1 1 1]
Entrada: [1 1 1], Salida: 1
[0 0 0]
Entrada: [0 0 0], Salida: 0


## Ejercicio 2: 

### Diseñar e implementar una unidad McCulloch–Pitts capaz de reconocer la letra "T" digitalizada en una matriz de 10 × 10 píxeles. Los píxeles oscuros deben codificarse como unos y los píxeles blancos como ceros.

In [3]:
import numpy as np

class McCullochPittsNeuron:
    def __init__(self, pesos, umbral):
        self.umbral=umbral
        self.pesos=pesos

    def activateT(self, entradas):
        igual_elementos=np.dot(self.pesos, entradas)
        #devuelve 1 si la suma es mayor o igual que el umbral, sino 0
        return 1 if igual_elementos >= self.umbral else 0

# Matriz que representa la letra "T" en una imagen 10x10
Matriz_original = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0
]

# Crear la neurona para reconocer la letra "T"
def reconoceT():
    # Pesos que corresponden a la matriz de la letra "T"
    pesos = Matriz_original
    # Umbral que corresponde a la cantidad de píxeles "oscuros" en la letra "T"
    umbral = sum(Matriz_original) * 1.0  # El umbral es el 90% de los píxeles que forman la "T"
    return McCullochPittsNeuron(pesos, umbral)


#creamos la neurona

neurona=reconoceT()


# T de prueba erronea
Matriz_prueba_mal = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0 
]


Matriz_prueba_bien = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0 
]

# Prueba de reconocimiento
output = neurona.activateT(Matriz_prueba_mal)
print(f"¿La imagen contiene una 'T'? {'Sí' if output == 1 else 'No'}")

¿La imagen contiene una 'T'? No
