### Primer ejercicio

![imagen](ejercio1.png "ejercicio uno") ![imagen](ejercio2.png "ejercicio uno") 

In [40]:
import numpy as np

x=np.array([1,2,5]) # vectores de entrada
b=np.array([1,2])  ##ballas
m=np.array([[3,1,4], ##matriz de pesos
            [2,7,5]])

transpuesta=m.T

ponderacion= np.dot(x, transpuesta)

print(ponderacion)

z=ponderacion+b

print(z)

def activa(z):
    return np.where(z>=0, 1,0)

y=activa(z)

print(y)

[25 41]
[26 43]
[1 1]


### Ejercicio 2

![imagen](ejercio22.png "ejercicio uno") ![imagen](ejercio23.PNG "ejercicio uno") ![imagen](ejercio24.PNG "ejercicio uno") 

In [42]:
import numpy as np
# vectores de entrada x
x=np.array([[1,2],
            [2,3],
            [4,1]])
# ballas b
b=np.array([2,3,2])
# matriz de pesos w
m=np.array([[2,5],
            [4,3],
            [2,1]])


trans=m.T

ponde= np.dot(x, trans)

z=ponde+b

print(z)





[[14 13  6]
 [21 20  9]
 [15 22 11]]
